Add server side Diffie-Hellman minimum modulus len
Crosse/SchannelGroupPolicy pull request #7
Opened 2018-06-13 13:10 UTC by IgorMilavec

Hello.

I have found a new document for TLS registry settings at https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings , which I have added to the list of resources.
Based on this document I have added a new setting for server side Diffie-Hellman minimum modulus length, which Microsoft recommends to set to 2048 bits.

Can you please accept the change?

BR Igor

2018-06-13 13:42 UTC, Crosse requested changes
The document you link to mentions that the DH key sizes are applicable to "…Windows 10, version 1507 and Windows Server 2016." However, the `DH` policy has a `supportedOn` value that would indicate that these new policies could apply to Windows 2003 and above. I'm not sure if you can apply `supportedOn` to individual elements, but if not, I think it'd be a good idea to make a new `policy` block, with an appropriate `supportedOn` value, for manipulating the minimum DH key size.

Does that make sense? It's been a while since I've touched a Windows server, much less administered one via Group Policy, so I'll have to defer to you for the best way forward.

2018-06-13 13:57 UTC, IgorMilavec commented
I agree with you to create a new policy element.
The document I linked specifies the supported registry settings for Windows 10 and Server 2016, however I have used this setting effectively on Windows Server 2008 R2. I will try to find a relevant document from MS to support this.

2018-06-18 19:56 UTC, IgorMilavec commented
I have committed the new version with a separate policy for DH minimum key length. Can you please review the change?

2018-06-18 20:05 UTC, Crosse approved these changes

2018-06-18 20:06 UTC, Crosse commented
Thanks! I've committed this with one small change (`s/shares/sizes/`).

2018-06-18 20:06 UTC, closed without merging